#!/bin/bash
total 20
-rwxr-xr-x 1 root root 26 Sep 28 12:37 0-current_working_directory
-rwxr--r-- 1 root root 25 Sep 28 13:08 1-listit
-rwxr--r-- 1 root root 15 Sep 29 03:39 2-bring_me_home
-rw-r--r-- 1 root root 12 Sep 29 03:46 3-listfiles
-rw-r--r-- 1 root root 71 Sep 28 11:35 README.md
